### PR TITLE
Added checkstyle config file and IDEA config files

### PR DESCRIPTION
**Pull request by devbridie**
Removes checkstyle configuration files and IntelliJ files from being tracked.

### CODE REVIEW

**Comment by HarmGriffioen** [comment]
Why do we remove checkstyle config? This means that Jenkins can have other checkstyle that we have right?

**Comment by PauluzzNL** [comment]
I think this is not the configuration file (for checkstyle) but actually some local data cache file?

**Comment by devbridie** [comment]
The configuration file (rules) are located in `checkstyle.xml`. The `.checkstyle` file only tells Eclipse where the rules are located. I haven't seen the file on your computers for what it's worth, only on mine. (Not sure why though!)

**Comment by PauluzzNL** [comment]
Thanks for the clarification :+1:

**Comment by HarmGriffioen** [comment]
:+1:

**Pull request merged**
