### PR TITLE
Checkstyle rules update.

### PR DESCRIPTION
**Pull request by PauluzzNL**
Updated checkstyle to allow 125 characters per line.

### CODE REVIEW

**Comment by devbridie** [comment]
Perhaps this is the time to get some other things changed as well? We could fix our diffs by making checkstyle check for "New Line At End Of File"s, and then setting that to windows.

**Comment by PauluzzNL** [comment]
Tried to find something good for the line endings but did not seem to be so easy. If anyone could fix something for that that'd be great. Maybe @erwinvaneyk or @trensen know how to enforce that?

**Comment by trensen** [comment]
You could ignore whitespace/line endings in diffs by adding `?w=1` to the end of the url. See the differences between [this](https://github.com/tygron-virtual-humans/tygron-connect/pull/105/files) and [this](https://github.com/tygron-virtual-humans/tygron-connect/pull/105/files?w=1). :smile:

EDIT: The number of lines added and deleted do change under the diff-tab, I'm not sure whether these (correct) numbers are used when merging, though.

**Comment by devbridie** [comment]
Added NewlineAtEndOfFile to our checkstyle configuration. :+1: on Paul's commit from me.

**Comment by PauluzzNL** [comment]
:+1: for Dereck's change

**Comment by JoeHarrison** [comment]
:+1:

**Pull request merged**
