### PR TITLE
Updates environment

### LINKED ISSUE #185: Failing when stakeholder is not selected
When a stakeholder can not be selected, we have to throw an exception instead of continue. This way the VH won't go trying to do stuff that it can not.

### PR DESCRIPTION
**Pull request by HarmGriffioen**
- Added buyLand action
- Failing when stakeholder selection fails, fixes #185

### CODE REVIEW

**Comment by PauluzzNL** [comment]
:+1:

**Comment by devbridie** [comment]
:+1:... but I think `Environment.setStakeholder()` should throw when it fails.

**Comment by HarmGriffioen** [comment]
That would be more elegant i guess, for if it is running without the environment part

**Comment by devbridie** [comment]
I like it. :+1:

Travis is being slow again though.

**Comment by PauluzzNL** [comment]
Also approve the new changes :+1:

**Pull request merged**
