### PR TITLE
Implemented JSON Handling for HTTP Api requests.

### PR DESCRIPTION
**Pull request by PauluzzNL**

### CODE REVIEW

**Comment by HarmGriffioen** [comment]
Fine by me :+1:

**Comment by devbridie** [comment]
Seems OK for now, could use some abstracting in the future. (see my new comments)

**Comment by devbridie** [comment]
You forgot the other instance of the same mistake.

**Comment by PauluzzNL** [comment]
Fixed :scream: :boom:

**Comment by devbridie** [comment]
Good job! :+1:

**Comment by nradenovic93** [comment]
:+1:  Okay

**Pull request merged**
