### PR TITLE
Eis updates

### PR DESCRIPTION
**Pull request by HarmGriffioen**
Updated environment with new percepts and actions.
- number of permits request
- available land percept
- all land percept

actions
- give money action
- ask money action

### CODE REVIEW

**Comment by PauluzzNL** [comment]
:+1: :rose:

**Comment by JoeHarrison** [comment]
:+1:

**Comment by JoeHarrison** [comment]
looks good, but will wait with merging untill manual test succeeds

**Comment by HarmGriffioen** [comment]
Manual tests succeed :smile:

**Comment by JoeHarrison** [comment]
cool

**Pull request merged**
