### PR TITLE
Esri polygon demo

### PR DESCRIPTION
**Pull request by JoeHarrison**
Demo wkt to esri geometry + example contains function

### CODE REVIEW

**Comment by HarmGriffioen** [comment]
Travis says :-1:

**Comment by HarmGriffioen** [comment]
Tests are missing for DemoGeometryLoader

**Comment by HarmGriffioen** [comment]
:+1:

**Comment by PauluzzNL** [comment]
Next time please link this to an issue and set the correct milestones/labels. Code itself is accepted.

**Pull request merged**
