### PR TITLE
Removed eclipse project files and added entries to gitignore

### PR DESCRIPTION
**Pull request by devbridie**
Removed @HarmGriffioen's project files from the environment project.

### CODE REVIEW

**Comment by devbridie** [comment]
Please ignore the travis notifications, it hasn't been setup yet.

**Comment by HarmGriffioen** [comment]
If the travis notifications get fixed by the other branch :+1:

**Comment by PauluzzNL** [comment]
Ik vind helemaal mooi :+1:

**Comment by devbridie** [comment]
Travis notification fix as per merge on f70a7ba. Closing, merging, and deleting as per majority.

**Pull request merged**
