### PR TITLE
Ead updates

### LINKED ISSUE #80: Update emergent architecture design

### PR DESCRIPTION
**Pull request by devbridie**
Added a class diagram, renamed Cache to Environment.

Fixes #80.

### CODE REVIEW

**Comment by devbridie** [comment]
Wait, I don't know why 67c2bfa is in this PR.

**Comment by devbridie** [comment]
Okay fixed it. :) Please review.

**Comment by PauluzzNL** [comment]
:+1: :hibiscus:

**Comment by devbridie** [comment]
I lost the files that were supposed to be here with a force push. :(

**Pull request closed without merging**
