### PR TITLE
Build based on provided function type.

### PR DESCRIPTION
**Pull request by nradenovic93**
Selects a function based on the type provided. Building and selecting land still works the same way. Set environment to reload every 10 seconds instead of every 2.5 seconds.

The caller of the build function has to provide an integer which determines the type of building project they want to place. Currently, 0 is for housing, 1 is for parks, and 2 is for parking lots.

The type of the function is determined in the Function class. Any expansion of building types or changes of values has to only be modified there. The Environment class only passes the provided value to Function.

### CODE REVIEW

**Comment by devbridie** [comment]
:+1:

**Comment by nradenovic93** [comment]
It's not necessary, but I comment out the reload function when I test the environment, so it doesn't overload the console with information. Do you want me to change it?

**Comment by devbridie** [comment]
It's fine, was just wondering if Stakeholders are mutable or not.

**Comment by HarmGriffioen** [comment]
:+1:

**Pull request merged**
