### PR TITLE
Implemented GET/POST requests in the TygronHTTP library. 

### PR DESCRIPTION
**Pull request by PauluzzNL**
Implemented GET/POST requests in the TygronHTTP library. 
Updated Demo HTTP to use this new library.

### CODE REVIEW

**Comment by JoeHarrison** [comment]
:-1: Maven dependency failt volgens Travis

**Comment by JoeHarrison** [comment]
:+1:

**Comment by HarmGriffioen** [comment]
Travis is taking a long time -_-

**Comment by devbridie** [comment]
Travis says OK. :+1:

**Comment by HarmGriffioen** [comment]
Travis adres :+1:

**Pull request merged**
