### PR TITLE
Emergent Architecture Design Draft

### PR DESCRIPTION
**Pull request by JoeHarrison**
Paar aanpassingen van vorige versie op Drive, samengewerkt met Dereck

### CODE REVIEW

**Comment by PauluzzNL** [comment]
:+1:

**Comment by devbridie** [comment]
I forgot to change the diagram of how our system structure works, there should be a poller in between the interface and the cache. Lemme update the document on drive.

**Comment by devbridie** [comment]
Fixed it!

**Comment by devbridie** [comment]
:+1: from me.

**Comment by PauluzzNL** [comment]
:+1:

**Pull request merged**
