### PR TITLE
Fixed PerceptTests to use Environment instead of Session.

### PR DESCRIPTION
**Pull request by devbridie**
Fixed percept tests. The test failed, why did Travis OK it?

### CODE REVIEW

**Comment by Buildwise** [comment]
Can one of the admins verify this patch?

**Comment by KolakCC** [comment]
ok to build

**Comment by PauluzzNL** [comment]
retest this please

**Comment by JoeHarrison** [comment]
:+1:

**Comment by PauluzzNL** [comment]
:+1: :heart:

**Pull request merged**
